# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

        Wap3\AdminBundle\Entity\Wap3AdminUser:
            id: wap3.admin.service.auth.encoder

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        admin_entity:
            entity:
              class: Wap3\AdminBundle\Entity\Wap3AdminUser
              property: login
        admin_in_memory:
            memory:
                users:
                    admin:
                        password: 12345
                        roles: [ROLE_ADMIN_USER, ROLE_ADMIN]
        admin:
          chain:
            providers: [admin_entity, admin_in_memory]
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin_secured_area:
            pattern: ^/admin/
            provider: admin
            anonymous: ~
            form_login:
                check_path: /admin/login_check
                login_path: /admin/login
                always_use_default_target_path: true
                default_target_path: /admin/
            logout:
                path:   /admin/logout
                target: /admin/
                invalidate_session: false

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/ausers$, roles: [ ROLE_ADMIN ] }
        - { path: ^/admin/auser/edit/*, roles: [ ROLE_ADMIN, ROLE_ADMIN_USER ] }
        - { path: ^/admin/auser/.*, roles: [ ROLE_ADMIN ] }
        - { path: ^/admin/.*, roles: [ROLE_ADMIN, ROLE_ADMIN_USER] }
        - { path: ^/admin$, roles: IS_AUTHENTICATED_ANONYMOUSLY }